# Generated by Django 2.2.15 on 2020-08-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_customuser_is_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
