# Generated by Django 2.2.15 on 2020-08-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='/static/default_picture.png', upload_to='profile_image'),
        ),
    ]
