# Generated by Django 2.2.15 on 2020-08-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_auto_20200825_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='/None/default_picture.png', upload_to='profile_image'),
        ),
    ]
