# Generated by Django 2.2.15 on 2020-09-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
