# Generated by Django 2.2.15 on 2020-09-21 10:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_management', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('date', models.DateField(auto_created=True, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('total', models.FloatField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.Product')),
            ],
        ),
    ]
