# Generated by Django 2.2.15 on 2020-09-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
