# Generated by Django 2.2.15 on 2020-09-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200921_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
    ]
